language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '10'
  - '12'
script:
  - yarn test:prod && yarn build
after_success:
  - yarn report-coverage
