version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - heapbottom
  - heapify
  - heappop
  - heappush
  - heappushpop
  - heapq
  - heapreplace
  - heaptop
  - nlargest
  - nsmallest
  - pushpop
  - unshift
ignoreWords: []
import: []
